name: shop_app_mixin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.7
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  flutter_facebook_auth: ^3.5.1
  sqflite: ^2.0.0+4
  path: ^1.8.0
  shared_preferences: ^2.0.7
  status_change: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  connectivity_plus: ^1.1.0
  image_picker: ^0.8.4+2
  firebase_storage: ^10.0.3
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.4

flutter_native_splash:
  # color: "#2E9AEB"
  background_image: "assets/splashScreen.png"
  image: assets/mixin.png
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf

